### PR TITLE
switch to 256 Mb

### PR DESCRIPTION
**Pull request by slaupster**
@knolleary is this workable to fit in lite ?

### CODE REVIEW

**Comment by knolleary** [comment]
@slaupster d'oh - just as I hit commit I remembered this will need changing as well:

https://github.com/ibmets/node-red-bluemix-starter/blob/master/package.json#L22

**Comment by knolleary** [comment]
Done - https://github.com/ibmets/node-red-bluemix-starter/commit/6e3ed5e3eca0e9389fa42e604de707faef509fcd

**Comment by slaupster** [comment]
@knolleary iirc 192 was ok for that ?

**Comment by slaupster** [comment]
cool ta!

**Pull request merged**
